# Generated by Django 2.1.7 on 2019-04-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_id', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('datasource', models.CharField(max_length=30)),
                ('datayear', models.IntegerField()),
                ('unit', models.CharField(max_length=10)),
                ('visualtype', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=20)),
                ('keyword', models.CharField(max_length=200)),
                ('datatype', models.CharField(max_length=30)),
                ('filepath', models.CharField(max_length=200)),
            ],
        ),
    ]
